replicaCount: 1

image:
  registry: docker.io
  repository: leogrv22/items
  tag: v1.0.0
  pullPolicy: IfNotPresent

env:
  APP_ENV: prod

secrets:
  SECRET_KEY: ""
  DATABASE_URL: ""

resources: {}

ingress:
  enabled: false
