global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000']
    metrics_path: /metrics

  - job_name: 'users-service'
    static_configs:
      - targets: ['users-service:8000']
    metrics_path: /metrics

  - job_name: 'items-service'
    static_configs:
      - targets: ['items-service:8000']
    metrics_path: /metrics

  - job_name: 'gateway-service'
    static_configs:
      - targets: ['gateway-service:8000']
    metrics_path: /metrics
